### ISSUE TITLE
[Bug]: 配置文件上传失败（github&gitee）

### ISSUE THREAD

**Issue by skinnyshy** [Kuingsmile/PicList#116]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.6.7

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

同步设置中测试了gitee和github，上传失败，仓库手动推送没有问题。

### 相关日志 | Logs

    at y.emit (node:events:513:28)
    at u.forEach.p.<computed> (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:610306)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
-------Error Stack End-------
2023-11-29 21:04:24 [PicList ERROR] upload manage.bak.json failed
2023-11-29 21:09:04 [PicList ERROR]
------Error Stack Begin------
HttpError: Bad credentials
    at /Applications/PicList.app/Contents/Resources/app.asar/index.js:2:833481
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324965
    at async Wh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324508)
    at async Kh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2323189)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2330142
    at async node:electron/js2c/browser_init:2:97553
-------Error Stack End-------
2023-11-29 21:09:04 [PicList ERROR] upload data.json failed
2023-11-29 21:09:05 [PicList ERROR]
------Error Stack Begin------
HttpError: Bad credentials
    at /Applications/PicList.app/Contents/Resources/app.asar/index.js:2:833481
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324965
    at async Wh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324508)
    at async Kh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2323189)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2330164
    at async node:electron/js2c/browser_init:2:97553
-------Error Stack End-------
2023-11-29 21:09:05 [PicList ERROR] upload data.bak.json failed
2023-11-29 21:09:06 [PicList ERROR]
------Error Stack Begin------
HttpError: Bad credentials
    at /Applications/PicList.app/Contents/Resources/app.asar/index.js:2:833481
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324965
    at async Wh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324508)
    at async Kh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2323189)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2330190
    at async node:electron/js2c/browser_init:2:97553
-------Error Stack End-------
2023-11-29 21:09:06 [PicList ERROR] upload manage.json failed
2023-11-29 21:09:07 [PicList ERROR]
------Error Stack Begin------
HttpError: Bad credentials
    at /Applications/PicList.app/Contents/Resources/app.asar/index.js:2:833481
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324965
    at async Wh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2324508)
    at async Kh (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2323189)
    at async /Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2330214
    at async node:electron/js2c/browser_init:2:97553
-------Error Stack End-------
2023-11-29 21:09:07 [PicList ERROR] upload manage.bak.json failed

**Comment by Kuingsmile** [comment]
github和gitee都报相同的错误么 我自己测试github是ok的 ，看下你的token权限是否设置完整

![image](https://github.com/Kuingsmile/PicList/assets/96409857/00af2d35-213b-4e93-b7bd-d63903f8fd8f)
![image](https://github.com/Kuingsmile/PicList/assets/96409857/8b203d4d-8fb0-400e-86f0-3441bb38aeff)

**Comment by skinnyshy** [comment]
> github和gitee都报相同的错误么 我自己测试github是ok的 ，看下你的token权限是否设置完整
> 
> ![image](https://private-user-images.githubusercontent.com/96409857/286612883-00af2d35-213b-4e93-b7bd-d63903f8fd8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDAxMzUsIm5iZiI6MTcwMTQzOTgzNSwicGF0aCI6Ii85NjQwOTg1Ny8yODY2MTI4ODMtMDBhZjJkMzUtMjEzYi00ZTkzLWI3YmQtZDYzOTAzZjhmZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE0MTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjA4MGE2MmE5ZGZiMjBjZTlmNmIzNDA5ODlhMzQ1ZDQ1ZTBjNmNlNjQ2NDg3MTRlMjFkYjM1M2UyMTA0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u0gjsJ_51ML_WO1vmsTfdS9qgHPGwUL28vQJGmGxjYc) ![image](https://private-user-images.githubusercontent.com/96409857/286613210-8b203d4d-8fb0-400e-86f0-3441bb38aeff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDAxMzUsIm5iZiI6MTcwMTQzOTgzNSwicGF0aCI6Ii85NjQwOTg1Ny8yODY2MTMyMTAtOGIyMDNkNGQtOGZiMC00MDBlLTg2ZjAtMzQ0MWJiMzhhZWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE0MTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ODJlZWJlYzc4ZTIzMmZkNWM1YTM2MDhhNTJlOTJlOTI0ZGFiMTE4ZTEzZTYxYjgzOGUwNzYxNzQyMzM4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-kKsggWIje8Dlz6Iyy5RgOFSKZxoGvpzmE-EQcVIIXg)

本地推送测试没有问题
<img width="1201" alt="image" src="https://github.com/Kuingsmile/PicList/assets/12553514/df021697-265d-4ce2-8be1-5f33c7b2d1bb">

<img width="776" alt="image" src="https://github.com/Kuingsmile/PicList/assets/12553514/59e2c6d9-2b92-4c81-ae7b-a1497a36f661">

<img width="972" alt="image" src="https://github.com/Kuingsmile/PicList/assets/12553514/6217eb42-6c18-41da-8ff9-624ce95a0425">

<img width="1197" alt="image" src="https://github.com/Kuingsmile/PicList/assets/12553514/f9b7be51-af34-4d68-8079-3bfeb0acdfb6">

**Comment by Kuingsmile** [comment]
有些奇怪 我出差回去看看哈

**Comment by Kuingsmile** [comment]
@skinnyshy 
![image](https://github.com/Kuingsmile/PicList/assets/96409857/9976b534-0ec1-4a37-b3f5-8ed4319710f7)
这里的报错是HttpError：Not Found了，不是之前的授权错误，我尝试进行复现，能复现相同报错信息的状况是用户名或仓库名错误

![image](https://github.com/Kuingsmile/PicList/assets/96409857/9faf6588-a974-4fc1-b951-7dd54bb710ca)
看到你这里的马赛克很长，这里是把仓库名也写进去了，就是写成`用户名/仓库名`了？

**Comment by skinnyshy** [comment]
我又检查了一下，确实是用户名拼写的问题，是我的锅，不好意思
