### ISSUE TITLE
[Bug]: 重复上传用一张图片会上传失败

### ISSUE THREAD

**Issue by cli-r** [Kuingsmile/PicList#129]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用typora上传图片，启用高级重命名功能和转码功能。一次图片上传成功后删除图片，再次上传时报错，实际上图片已经上传成功，但是不显示。个人推测是转码缓存导致上传检测失败。配置没有问题，因为换用另一张图片上传成功。

补充，与文件名有关，修改文件名与原文件名不同后上传成功。

我在上传时因为调试s3配置，曾分别使用sftp和s3上传同一张图片，不知道是不是引发问题的原因。

### 相关日志 | Logs

2023-12-31 16:41:37 [PicList INFO] [PicList Server] get the request {"list":["D:\\Onedrive\\应用\\remotely-save\\blog\\assets\\P1041621_1.PNG"]} 
2023-12-31 16:41:37 [PicList INFO] [PicList Server] upload files in list 
2023-12-31 16:41:37 [PicList INFO] Compress or convert image 
2023-12-31 16:41:38 [PicList INFO] Before transform 
2023-12-31 16:41:38 [PicList INFO] Transforming... Current transformer is [path] 
2023-12-31 16:41:38 [PicList INFO] Before upload 
2023-12-31 16:41:38 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-12-31 16:41:38 [PicList INFO] Uploading... Current uploader is [sftpplist] 
2023-12-31 16:41:40 [PicList WARN] failed 
2023-12-31 16:41:40 [PicList ERROR] 
------Error Stack Begin------
Error: dest already exists.
    at doRename (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:32:34)
    at Object.moveSync (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:17:10)
    at Object.Zt [as handle] (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:70180)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async dt.doUpload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:37180)
    at async dt.start (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:35932)
    at async Lr.upload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:128266)
    at async Object.upload (D:\Program Files\PicList\resources\app.asar\index.js:8:2121299)
    at async Bd (D:\Program Files\PicList\resources\app.asar\index.js:8:2295861)
    at async D:\Program Files\PicList\resources\app.asar\index.js:8:2300359
-------Error Stack End------- 
2023-12-31 16:41:40 [PicList ERROR] 
------Error Stack Begin------
Error: dest already exists.
    at doRename (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:32:34)
    at Object.moveSync (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:17:10)
    at Object.Zt [as handle] (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:70180)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async dt.doUpload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:37180)
    at async dt.start (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:35932)
    at async Lr.upload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:128266)
    at async Object.upload (D:\Program Files\PicList\resources\app.asar\index.js:8:2121299)
    at async Bd (D:\Program Files\PicList\resources\app.asar\index.js:8:2295861)
    at async D:\Program Files\PicList\resources\app.asar\index.js:8:2300359
-------Error Stack End------- 
2023-12-31 16:41:40 [PicList INFO] [PicList Server] upload result  
2023-12-31 16:41:40 [PicList WARN] [PicList Server] upload failed, see piclist.log for more detail ↑ 
2023-12-31 16:42:52 [PicList INFO] Compress or convert image 
2023-12-31 16:42:53 [PicList INFO] Before transform 
2023-12-31 16:42:53 [PicList INFO] Transforming... Current transformer is [path] 
2023-12-31 16:42:53 [PicList INFO] Before upload 
2023-12-31 16:42:53 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-12-31 16:42:53 [PicList INFO] Uploading... Current uploader is [sftpplist] 
2023-12-31 16:42:55 [PicList WARN] failed 
2023-12-31 16:42:55 [PicList ERROR] 
------Error Stack Begin------
Error: dest already exists.
    at doRename (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:32:34)
    at Object.moveSync (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:17:10)
    at Object.Zt [as handle] (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:70180)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async dt.doUpload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:37180)
    at async dt.start (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:35932)
    at async Lr.upload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:128266)
    at async Object.upload (D:\Program Files\PicList\resources\app.asar\index.js:8:2121299)
    at async Bd (D:\Program Files\PicList\resources\app.asar\index.js:8:2295861)
-------Error Stack End------- 
2023-12-31 16:42:55 [PicList ERROR] 
------Error Stack Begin------
Error: dest already exists.
    at doRename (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:32:34)
    at Object.moveSync (D:\Program Files\PicList\resources\app.asar\node_modules\fs-extra\lib\move\move-sync.js:17:10)
    at Object.Zt [as handle] (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:70180)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async dt.doUpload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:37180)
    at async dt.start (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:35932)
    at async Lr.upload (D:\Program Files\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:128266)
    at async Object.upload (D:\Program Files\PicList\resources\app.asar\index.js:8:2121299)
    at async Bd (D:\Program Files\PicList\resources\app.asar\index.js:8:2295861)
-------Error Stack End-------

**Comment by Kuingsmile** [comment]
假期结束后我测试下

**Comment by Kuingsmile** [comment]
如果重复上传文件名相同的图片，会因为已存在该文件导致失败，后续会添加一个开关选项用来控制是否覆盖上传

**Comment by Kuingsmile** [comment]
已修复
