### ISSUE TITLE
[Bug]: PicList 2.7.1版本不能安装s3插件

### ISSUE THREAD

**Issue by Z3n1th1** [Kuingsmile/PicList#144]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.1 -x64

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

不能安装s3插件（在离线安装后也是不行的），并且出现该报错后PicList会自动闪退，虽然看日志文件报错好像是s3插件的问题（（我用的picgo的2.4.0的beta6也不能安装
![image](https://github.com/Kuingsmile/PicList/assets/150457049/13f8d4c1-a6ed-4f38-b321-a822a847359d)

### 相关日志 | Logs

Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\piclist\node_modules\picgo-plugin-s3\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:371:19)
    at Module._findPath (node:internal/modules/cjs/loader:584:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:949:27)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Pr.getPlugin (D:\111111\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:85657)
    at Pr.registerPlugin (D:\111111\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:84780)
-------Error Stack End------- 
2024-01-19 20:54:26 [PicList SUCCESS] 插件安装成功 
2024-01-19 20:55:31 [PicList ERROR] 
------Error Stack Begin------
Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\piclist\node_modules\picgo-plugin-s3\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:371:19)
    at Module._findPath (node:internal/modules/cjs/loader:584:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:949:27)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Pr.getPlugin (D:\111111\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:85657)
    at Pr.registerPlugin (D:\111111\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:84780)
-------Error Stack End------- 
2024-01-19 20:55:32 [PicList INFO] [PicList Server] is listening at 36677 of 0.0.0.0 
2024-01-19 20:55:32 [PicList INFO] File server is running, http://localhost:36699

**Comment by Z3n1th1** [comment]
看到了之前那个问题也是s3安装不了的问题说下个版本会把s3加入内置图床，我以为是2.7.1（但是还是没有）希望下次更新能加入，用的cloudflare的r2想要用PicList来同步图片（（个人偏喜欢PicList一些

**Comment by Kuingsmile** [comment]
> 看到了之前那个问题也是s3安装不了的问题说下个版本会把s3加入内置图床，我以为是2.7.1（但是还是没有）希望下次更新能加入，用的cloudflare的r2想要用PicList来同步图片（（个人偏喜欢PicList一些

已经在最新的提交里添加了内置s3,会在2.7.2打包发布，预计在下周一左右
