### ISSUE TITLE
[Bug]: 使用docker安装，无法上传图片

### ISSUE THREAD

**Issue by yzgolden86** [Kuingsmile/PicList#163]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.7.3

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

在远程服务器docker部署了piclist，obsidian中上传图片时，提示
![image](https://github.com/Kuingsmile/PicList/assets/56377040/73c08097-2c1e-4e63-9c14-bed9dc24acaf)
应该是图片上传失败，打印docker 日志，应该是没有找到配置文件，我参看文档没有找到所示位置，我只是在/root/piclist/config.json做了修改，也尝试新建了data.json文件，也无果，求教

### 相关日志 | Logs

2024-02-18 20:01:01 [PicList INFO] Before transform 
2024-02-18 20:01:02 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:01:03 [PicList INFO] Before upload 
2024-02-18 20:01:03 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:01:03 [PicList WARN] failed 
2024-02-18 20:01:03 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End------- 
2024-02-18 20:03:23 [PicList INFO] Before transform 
2024-02-18 20:03:23 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:03:23 [PicList INFO] Before upload 
2024-02-18 20:03:23 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:03:23 [PicList WARN] failed 
2024-02-18 20:03:23 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End------- 
2024-02-18 20:16:54 [PicList INFO] Before transform 
2024-02-18 20:16:54 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:16:54 [PicList INFO] Before upload 
2024-02-18 20:16:54 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:16:54 [PicList WARN] failed 
2024-02-18 20:16:54 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End------- 
2024-02-18 20:28:35 [PicList INFO] Before transform 
2024-02-18 20:28:35 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:28:35 [PicList INFO] Before upload 
2024-02-18 20:28:35 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:28:35 [PicList WARN] failed 
2024-02-18 20:28:35 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End------- 
2024-02-18 20:43:34 [PicList INFO] Before transform 
2024-02-18 20:43:34 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:43:34 [PicList INFO] Before upload 
2024-02-18 20:43:34 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:43:34 [PicList WARN] failed 
2024-02-18 20:43:34 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End------- 
2024-02-18 20:45:55 [PicList INFO] Before transform 
2024-02-18 20:45:55 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:45:55 [PicList INFO] Before upload 
2024-02-18 20:45:55 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:45:55 [PicList WARN] failed 
2024-02-18 20:45:55 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End------- 
2024-02-18 20:59:02 [PicList INFO] Before transform 
2024-02-18 20:59:02 [PicList INFO] Transforming... Current transformer is [path] 
2024-02-18 20:59:02 [PicList INFO] Before upload 
2024-02-18 20:59:02 [PicList INFO] Uploading... Current uploader is [local] 
2024-02-18 20:59:02 [PicList WARN] failed 
2024-02-18 20:59:02 [PicList ERROR] 
------Error Stack Begin------
Error: Can not find local config!
    at Object.sr [as handle] (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:66866)
    at Bt.doUpload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:37791)
    at Bt.start (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:36531)
    at async qr.upload (/usr/local/share/.config/yarn/global/node_modules/piclist/dist/index.cjs.js:1:147571)
    at async /usr/local/share/.config/yarn/global/node_modules/piclist/bin/picgo-server:202:22
-------Error Stack End-------

**Comment by yzgolden86** [comment]
{
  "picBed": {
    "uploader": "qiniu",
    "current": "qiniu",
    "qiniu": {
      "accessKeyId": "xxx",
      "accessKeySecret": "xxx",
      "bucket": "xx",
      "area": "na0",
      "path": "test/",
      "customUrl": "xxx",
      "options": ""
    }
  }
}
配置文件的格式我是这样写的，obsidian中的上传接口我是这样填的，http://域名:36677/upload?key=xxx

**Comment by Kuingsmile** [comment]
运行docker的时候的-v参数或者docker-compose文件的volumes参数，比如
```bash
docker run -d \
  --name piclist \
  --restart always \
  -p 36677:36677 \
  -v "./piclist:/root/.piclist" \
  kuingsmile/piclist:latest \
  node /usr/local/bin/picgo-server -k piclist123456
```

其中的`-v "./piclist:/root/.piclist"`里的第一个`./piclist`指的是你的config.json文件所在的目录，比如你的配置文件在`/root/piclist/config.json`，那就需要改成`-v "/root/piclist:/root/.piclist"`
