### ISSUE TITLE
[Bug]: Mac上用 typora 上传图片报错

### ISSUE THREAD

**Issue by TtlyLynzie** [Kuingsmile/PicList#222]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

<img width="497" alt="image" src="https://github.com/user-attachments/assets/125e6b15-5a3f-46e8-a84b-8ee9224b58ce">

### 相关日志 | Logs

2024-07-14 20:47:28 [PicList INFO] detect second instance 
2024-07-14 20:47:28 [PicList INFO] cli -> uploading files from cli /Applications/Typora.app/Contents/Resources/TypeMark/assets/icon/icon_512x512.png /Applications/Typora.app/Contents/Resources/TypeMark/assets/icon/icon_256x256.png 
2024-07-14 20:47:28 [PicList INFO] Before transform 
2024-07-14 20:47:28 [PicList INFO] Transforming... Current transformer is [path] 
2024-07-14 20:47:28 [PicList INFO] Before upload 
2024-07-14 20:47:28 [PicList INFO] beforeUploadPlugins: renameFn running 
2024-07-14 20:47:28 [PicList INFO] create rename window 
2024-07-14 20:47:28 [PicList INFO] create rename window 
2024-07-14 20:47:28 [PicList INFO] rename window ready, wait for rename... 
2024-07-14 20:47:28 [PicList INFO] rename window ready, wait for rename... 
2024-07-14 20:47:29 [PicList INFO] Uploading... Current uploader is [smms] 
2024-07-14 20:47:30 [PicList WARN] failed 
2024-07-14 20:47:30 [PicList ERROR] 
------Error Stack Begin------
Error: This image has been blocked, please contact webmaster for more information.
    at Object.mr [as handle] (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:86421)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Gt.doUpload (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:46972)
    at async Gt.start (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:45814)
    at async Zr.upload (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:152511)
    at async Object.upload (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2101967)
    at async wo (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2109816)
-------Error Stack End------- 
2024-07-14 20:47:30 [PicList ERROR] 
------Error Stack Begin------
Error: This image has been blocked, please contact webmaster for more information.
    at Object.mr [as handle] (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:86421)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Gt.doUpload (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:46972)
    at async Gt.start (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:45814)
    at async Zr.upload (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/dist/index.cjs.js:1:152511)
    at async Object.upload (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2101967)
    at async wo (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:2109816)
-------Error Stack End-------

**Comment by Kuingsmile** [comment]
Error: This image has been blocked, please contact webmaster for more information.

Typora的默认测试图片被smms给屏蔽了，所以会报错，不用管，实际是没问题的
