### ISSUE TITLE
[Bug]: 本地图床上传失败

### ISSUE THREAD

**Issue by jianwu111** [Kuingsmile/PicList#260]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

配置：
也试过 `E:\图片\assets\` 依旧不行，尝试过重新安装 PicList，也不行
![image](https://github.com/user-attachments/assets/a60df2a3-9a92-4261-8d62-18f9bd6ac33d)

### 相关日志 | Logs

常规日志：
```log
2024-10-29 09:41:19 [PicList INFO] Before transform 
2024-10-29 09:41:19 [PicList INFO] Compress or convert image 
2024-10-29 09:41:20 [PicList INFO] Transforming... Current transformer is [path] 
2024-10-29 09:41:20 [PicList INFO] Before upload 
2024-10-29 09:41:20 [PicList INFO] beforeUploadPlugins: renameFn running 
2024-10-29 09:41:20 [PicList INFO] Uploading... Current uploader is [local] 
2024-10-29 09:41:20 [PicList WARN] failed 
2024-10-29 09:41:20 [PicList ERROR] 
------Error Stack Begin------
Error: failed to upload image
    at Object.hr [as handle] (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:74124)
    at Gt.doUpload (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:47381)
    at Gt.start (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:44224)
    at async un.upload (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:157056)
    at async Object.upload (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:2103322)
    at async No (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:2107634)
    at async IpcMainImpl.rpcEventHandler (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:2467869)
-------Error Stack End------- 
2024-10-29 09:41:20 [PicList ERROR] 
------Error Stack Begin------
Error: failed to upload image
    at Object.hr [as handle] (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:74124)
    at Gt.doUpload (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:47381)
    at Gt.start (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:44224)
    at async un.upload (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:157056)
    at async Object.upload (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:2103322)
    at async No (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:2107634)
    at async IpcMainImpl.rpcEventHandler (C:\Users\简悟\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:2467869)
-------Error Stack End------- 
```

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/dda26cfa-4944-43e4-8912-1e84d3543113)
我这样是没问题的呀

**Comment by Kuingsmile** [comment]
以管理员身份启动PicList试试

**Comment by jianwu111** [comment]
> 以管理员身份启动PicList试试

已解决，原因是 data.json 有点问题，删掉重新打开就好了
