### ISSUE TITLE
[Bug]: Mac版本WebDav模式下高级重命名出错

### ISSUE THREAD

**Issue by siben168** [Kuingsmile/PicList#278]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

2.9.6

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

想通过 WebDAV 上传图片实现  “月/日/图片名” 的目录管理结构，看到很多资料可以通过高级重命名实现，但是 mac 最新版实验后发现 403 forbidden 错误。

已经测试过如下重命名配置 :
1.  {Y}-{m}-{d}-{filename}，  这个可以成功上传，说明 webdav server 没有问题。
2. {Y}-{m}-{d}/{filename}, 只要带了目录符号 “/”，就会报 403 错误。

还排查了其他可能性：
- 用同一个webdav 账号在其他客户端建立文件夹是 ok 的，说明建立文件夹权限没有问题。

<img width="839" alt="image" src="https://github.com/user-attachments/assets/6494f89e-6fc1-4979-94db-316d9add0907" />

### 相关日志 | Logs

2024-12-18 17:38:11 [PicList ERROR] 
------Error Stack Begin------
Error: Invalid response: 403 Forbidden
    at createErrorFromResponse (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/node_modules/webdav/dist/node/response.js:10:15)
    at handleResponseCode (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/node_modules/webdav/dist/node/response.js:21:19)
    at /Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/node_modules/webdav/dist/node/operations/putFileContents.js:91:59
    at step (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/node_modules/webdav/dist/node/operations/putFileContents.js:33:23)
    at Object.next (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/node_modules/webdav/dist/node/operations/putFileContents.js:14:53)
    at fulfilled (/Applications/PicList.app/Contents/Resources/app.asar/node_modules/piclist/node_modules/webdav/dist/node/operations/putFileContents.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
-------Error Stack End-------

**Comment by Kuingsmile** [comment]
新建文件夹的逻辑有点问题，没有兼容高级重命名，下个版本会修复
