### ISSUE TITLE
[Bug]: 删除相册中的图片时，程序意外关闭

### ISSUE THREAD

**Issue by JeffreyZeng-dev** [Kuingsmile/PicList#279]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://piclist.cn/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v2.9.5

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

删除相册中的图片，程序直接自己退出了

### 相关日志 | Logs

2024-12-17 14:48:05 [PicList ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of undefined (reading 'syncDelete')
    at un.onDelete (C:\Users\Turbo\AppData\Roaming\piclist\node_modules\picgo-plugin-lankong\dist\index.js:20:39)
    at un.emit (node:events:513:28)
    at Timeout._onTimeout (D:\PicListData\PicList\resources\app.asar\index.js:8:2446999)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
-------Error Stack End------- 
2024-12-17 14:48:23 [PicList ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of undefined (reading 'syncDelete')
    at un.onDelete (C:\Users\Turbo\AppData\Roaming\piclist\node_modules\picgo-plugin-lankong\dist\index.js:20:39)
    at un.emit (node:events:513:28)
    at Timeout._onTimeout (D:\PicListData\PicList\resources\app.asar\index.js:8:2446999)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
-------Error Stack End------- 
2024-12-19 09:49:51 [PicList ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of undefined (reading 'syncDelete')
    at un.onDelete (C:\Users\Turbo\AppData\Roaming\piclist\node_modules\picgo-plugin-lankong\dist\index.js:20:39)
    at un.emit (node:events:513:28)
    at Timeout._onTimeout (D:\PicListData\PicList\resources\app.asar\index.js:8:2446999)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
-------Error Stack End-------

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicList/issues/111
参考置顶issue

**Comment by JeffreyZeng-dev** [comment]
> #111 参考置顶issue

我使用的是Piclist内置的兰空图床，未使用lankong插件

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/d8cefcf5-e27a-4b40-811a-a9203b3370a2)
你的报错显示来自插件呀

**Comment by JeffreyZeng-dev** [comment]
> ![image](https://private-user-images.githubusercontent.com/96409857/397188549-d8cefcf5-e27a-4b40-811a-a9203b3370a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzQzMTMsIm5iZiI6MTczNDU3NDAxMywicGF0aCI6Ii85NjQwOTg1Ny8zOTcxODg1NDktZDhjZWZjZjUtZTI3YS00YjQwLTgxMWEtYTkyMDNiMzM3MGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAyMDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMDVkZDUzZTdjY2JmNzhhZDVmN2JhNjhmZDM4OTNjNmM5YzdkNjZhOWNkNjVlYzg2Y2UyOGI5ZGMzNWNlNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oXQLTkUXfa1oVr0cqpLfSEeX_zezEzTT7UWsEGCLjJM) 你的报错显示来自插件呀

是什么原因导致 我不太清楚，不过我确实是下载了该插件，但是我从未配置过该插件，只配置了内置的兰空图床，目前已经卸载了lankong插件，已无问题，感谢你提供的解决方案。

**Comment by Kuingsmile** [comment]
这插件有问题，会主动监听删除事件，但如果只是安装了没有配置，就会出错
