### ISSUE TITLE
[Bug]: 一旦勾选“上传前重命名”，上传图片时PicList就会闪退。

### ISSUE THREAD

**Issue by ThomasXU-17** [Kuingsmile/PicList#58]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.9.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

一旦勾选“上传前重命名”，上传图片时PicList就会闪退。（Windows11）
如果单独使用“时间戳命名”或者“高级重命名”，则功能正常。

### 相关日志 | Logs

2023-06-02 16:29:53 [PicList INFO] [PicList Server] is listening at 36677 
2023-06-02 16:40:45 [PicList INFO] [PicList Server] get the request {"list":["E:\\Icon\\XXY_icon\\XXY_icon_color.jpg"]} 
2023-06-02 16:40:45 [PicList INFO] [PicList Server] upload files in list 
2023-06-02 16:40:55 [PicList INFO] [PicList Server] get the request {"list":["E:\\Icon\\XXY_icon\\XXY_icon_color.jpg"]} 
2023-06-02 16:40:55 [PicList INFO] [PicList Server] upload files in list 
2023-06-02 16:41:05 [PicList INFO] Before transform 
2023-06-02 16:41:05 [PicList INFO] Transforming... Current transformer is [path] 
2023-06-02 16:41:05 [PicList INFO] Before upload 
2023-06-02 16:41:05 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-06-02 16:41:29 [PicList INFO] [PicList Server] is listening at 36677 
2023-06-02 16:42:54 [PicList INFO] [PicList Server] get the request {"list":["E:\\Icon\\XXY_icon\\XXY_icon_color.jpg"]} 
2023-06-02 16:42:54 [PicList INFO] [PicList Server] upload files in list 
2023-06-02 16:42:54 [PicList INFO] Before transform 
2023-06-02 16:42:54 [PicList INFO] Transforming... Current transformer is [path] 
2023-06-02 16:42:54 [PicList INFO] Before upload 
2023-06-02 16:42:54 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-06-02 16:43:13 [PicList INFO] [PicList Server] is listening at 36677 
2023-06-02 16:44:41 [PicList INFO] Before transform 
2023-06-02 16:44:41 [PicList INFO] Transforming... Current transformer is [path] 
2023-06-02 16:44:42 [PicList INFO] Before upload 
2023-06-02 16:44:42 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-06-02 16:44:53 [PicList INFO] [PicList Server] is listening at 36677 
2023-06-02 16:46:45 [PicList INFO] Before transform 
2023-06-02 16:46:45 [PicList INFO] Transforming... Current transformer is [path] 
2023-06-02 16:46:46 [PicList INFO] Before upload 
2023-06-02 16:46:46 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-06-02 16:47:00 [PicList INFO] [PicList Server] is listening at 36677 
2023-06-02 16:49:06 [PicList INFO] [PicList Server] is listening at 36677 
2023-06-02 16:49:28 [PicList INFO] Before transform 
2023-06-02 16:49:28 [PicList INFO] Transforming... Current transformer is [path]

**Comment by Kuingsmile** [comment]
我在我的win11 + 1.9.3版本上没有复现出来，检查一下和日志文件同目录的`piclist-gui-local.log`这个文件的内容，看下在闪退时有记录的报错日志么

**Comment by ThomasXU-17** [comment]
------Error Stack Begin------
TypeError: Error processing argument at index 0, conversion failure from 
    at Object.callback (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1752100)
    at Object.create (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1753332)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754845
    at Array.map (<anonymous>)
    at Object.handle (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754733)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33822
    at Array.map (<anonymous>)
    at gt.handlePlugins (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33756)
    at gt.beforeUpload (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:32777)
    at gt.start (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:31871)
-------Error Stack End------- 
2023-06-02 16:42:54 [PicList ERROR] 
------Error Stack Begin------
TypeError: Error processing argument at index 0, conversion failure from 
    at Object.callback (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1752100)
    at Object.create (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1753332)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754845
    at Array.map (<anonymous>)
    at Object.handle (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754733)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33822
    at Array.map (<anonymous>)
    at gt.handlePlugins (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33756)
    at gt.beforeUpload (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:32777)
    at gt.start (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:31871)
-------Error Stack End------- 
2023-06-02 16:44:42 [PicList ERROR] 
------Error Stack Begin------
TypeError: Error processing argument at index 0, conversion failure from 
    at Object.callback (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1752100)
    at Object.create (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1753332)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754845
    at Array.map (<anonymous>)
    at Object.handle (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754733)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33822
    at Array.map (<anonymous>)
    at gt.handlePlugins (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33756)
    at gt.beforeUpload (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:32777)
    at gt.start (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:31871)
-------Error Stack End------- 
2023-06-02 16:46:45 [PicList ERROR] 
------Error Stack Begin------
TypeError: Error processing argument at index 0, conversion failure from 
    at Object.callback (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1752100)
    at Object.create (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1753332)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754845
    at Array.map (<anonymous>)
    at Object.handle (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754733)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33822
    at Array.map (<anonymous>)
    at gt.handlePlugins (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33756)
    at gt.beforeUpload (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:32777)
    at gt.start (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:31871)
-------Error Stack End------- 
2023-06-02 16:49:28 [PicList ERROR] 
------Error Stack Begin------
TypeError: Error processing argument at index 1, conversion failure from 
    at Object.callback (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1752100)
    at Object.create (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1753332)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754845
    at Array.map (<anonymous>)
    at Object.handle (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\index.js:8:1754733)
    at D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33822
    at Array.map (<anonymous>)
    at gt.handlePlugins (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:33756)
    at gt.beforeUpload (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:32777)
    at gt.start (D:\Users\Lenovo\AppData\Local\Programs\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js:1:31871)
-------Error Stack End-------

**Comment by Kuingsmile** [comment]
ok 看起来是在一个地方崩溃的，麻烦您可以提供下更详细的复现方法么，如下几个问题上传的是文件还是剪贴板图片，

**Comment by Kuingsmile** [comment]
ok 看起来是在一个地方崩溃的，麻烦您可以提供下更详细的复现方法么，如下几个问题：
1. 是直接从piclist上传还是从typora或者obsidian上传
2. 上传的是文件还是剪贴板图片
3. 使用的哪个图床平台
4. 开启上传前重命名的时候，是否还同时开启了时间戳重命名或高级重命名

我去检查下代码和尝试进行下复现

**Comment by ThomasXU-17** [comment]
1. 无论是piclist，还是obsidian都是奔溃
2. 上传文件和剪贴板没有差别
3. 腾讯cos
4. 无论是否开启时间戳重命名或高级重命名，只要开启“上传前重命名”都会奔溃。而且，只要不开启““上传前重命名”，时间戳重命名或高级重命名都运行正常。

**Comment by Kuingsmile** [comment]
> 1. 无论是piclist，还是obsidian都是奔溃
> 2. 上传文件和剪贴板没有差别
> 3. 腾讯cos
> 4. 无论是否开启时间戳重命名或高级重命名，只要开启“上传前重命名”都会奔溃。而且，只要不开启““上传前重命名”，时间戳重命名或高级重命名都运行正常。

好的~ 

不过我用cos也复现不出来。。尴尬o(╯□╰)o

![image](https://github.com/Kuingsmile/PicList/assets/96409857/62245523-4509-465e-a68c-facb5c626142)

**Comment by Kuingsmile** [comment]
我先根据日志查一下报错那几行的代码看看吧

**Comment by Kuingsmile** [comment]
看了下报错的地方的代码，应该是beforeUpload阶段运行插件的时候报的错，请问您安装了什么插件么

**Comment by Kuingsmile** [comment]
代码部分未发现明显异常，使用电脑全新安装1.9.3版本也无法进行复现，在有更多的信息提供之前，暂时关闭issue。

**Comment by xiang0805** [comment]
### PicList的版本 | PicList Version
v2.8.6
---
### 系统信息 | System Information
Ubuntu 22.04.4 LTS
---
### 問題重現| Bug reproduce

 一旦勾選“上傳前重命名”，上傳圖片時PicList就會閃退。  
 如果單獨使用“時間戳命名”或“進階重命名”，則功能正常。
 目前測試點擊主視窗上傳會有問題，但是點擊mini視窗就可以正常運作。

![output3](https://github.com/Kuingsmile/PicList/assets/77910492/ec0c83b9-4081-43ea-92b3-c262afc53c84)

**Comment by xiang0805** [comment]
@Kuingsmile

**Comment by xiang0805** [comment]
@Kuingsmile

**Comment by Kuingsmile** [comment]
> 
> @Kuingsmile 
> 

请新开issue并提供更详细的复现方式，我测试了手动重命名没有复现，提供下日志文件夹下的piclist-gui-local

**Comment by Kuingsmile** [comment]
> 
> @Kuingsmile 
> 

请新开issue并提供更详细的复现方式，我测试了手动重命名没有复现，请提供下日志文件夹下的piclist-gui-local.log文件的报错信息

**Comment by Kuingsmile** [comment]
@ThomasXU-17 @xiang0805 感谢各位 时隔一年我终于找到触发bug的方法和原因了。。。

**Comment by Kuingsmile** [comment]
已修复 感谢各位的反馈
