### ISSUE TITLE
[Bug]: 在使用 yourls 作为短链服务时 app 卡退

### ISSUE THREAD

**Issue by Mrered** [Kuingsmile/PicList#72]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.9.7

### 系统信息 | System Information

Mac(arm64)

## yourls 短链服务域名

填写的是 example.com 形式的域名，没写http(s)://
下面日志中也隐去了我的真实域名，用 example.com 代替

## signature 

填写的是十位的字符串

## 现象

- 在这种配置下，使用检测剪贴板自动上传会闪退；
- 在不使用短链接服务时就不会闪退。

### 相关日志 | Logs

piclist.log

```log
2023-07-13 08:22:48 [PicList INFO] [PicList Server] is listening at 36677 
2023-07-13 09:06:06 [PicList INFO] clipboard changed 
2023-07-13 09:06:29 [PicList INFO] Compress or convert image 
2023-07-13 09:06:31 [PicList INFO] Before transform 
2023-07-13 09:06:31 [PicList INFO] Transforming... Current transformer is [path] 
2023-07-13 09:06:43 [PicList INFO] Before upload 
2023-07-13 09:06:43 [PicList INFO] beforeUploadPlugins: renameFn running 
2023-07-13 09:06:43 [PicList INFO] Uploading... Current uploader is [aws-s3] 
2023-07-13 09:06:55 [PicList SUCCESS] 
https://file.example.com/2023/07/025d1581cb44980946e62e2bd1b8f3eb.webp 
```

piclist-gui-local.log

```log
2023-07-13 09:06:57 [PicList ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of undefined (reading 'data')
    at Da (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:1805253)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Wa (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:1815887)
    at async mm (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:1950014)
-------Error Stack End------- 
2023-07-13 09:06:57 [PicList ERROR] 
------Error Stack Begin------
TypeError: Object has been destroyed
    at wl (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:1990425)
    at EventEmitter.<anonymous> (/Applications/PicList.app/Contents/Resources/app.asar/index.js:8:1988992)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
-------Error Stack End------- 
```

**Comment by Mrered** [comment]
在使用长链接完成上传后，去图库里查看内容，切换到短链接模式，点复制 URL 时无任何响应。

**Comment by Kuingsmile** [comment]
@Mrered 请在域名前根据实际情况添加http://或https://，另外这里在1.9.8版本会进行优化
