### ISSUE TITLE
s3插件加载失败

### ISSUE THREAD

**Issue by OneYangCrown** [Kuingsmile/PicList#78]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

v1.9.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

PicGo（v2.3.1）能正常安装加载s3插件

node（v18.17.0）

![](https://github.com/Kuingsmile/PicList/assets/120536970/f0ec5b29-9f16-4cf5-8a7b-67e119a27c63)
![](https://github.com/Kuingsmile/PicList/assets/120536970/06f528cc-e0ca-4c38-9718-6e1b87541f9b)

### 相关日志 | Logs

2023-07-28 15:42:19 [PicList ERROR] 
------Error Stack Begin------
Error: Cannot find module './validator'
Require stack:
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\fast-xml-parser\src\fxp.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\protocols\Aws_query.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\commands\AssumeRoleCommand.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\defaultStsRoleAssumers.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\STSClient.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\index.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-s3\dist-cjs\index.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\picgo-plugin-s3\dist\uploader.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\picgo-plugin-s3\dist\index.js
- C:\Softwares\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js
- C:\Softwares\PicList\resources\app.asar\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\piclist\node_modules\fast-xml-parser\src\fxp.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
-------Error Stack End------- 
2023-07-28 15:42:19 [PicList SUCCESS] 插件安装成功 
2023-07-28 15:42:29 [PicList ERROR] 
------Error Stack Begin------
Error: Cannot find module './validator'
Require stack:
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\fast-xml-parser\src\fxp.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\protocols\Aws_query.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\commands\AssumeRoleCommand.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\defaultStsRoleAssumers.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\STSClient.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-sts\dist-cjs\index.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\@aws-sdk\client-s3\dist-cjs\index.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\picgo-plugin-s3\dist\uploader.js
- C:\Users\Admin\AppData\Roaming\piclist\node_modules\picgo-plugin-s3\dist\index.js
- C:\Softwares\PicList\resources\app.asar\node_modules\piclist\dist\index.cjs.js
- C:\Softwares\PicList\resources\app.asar\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\piclist\node_modules\fast-xml-parser\src\fxp.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
-------Error Stack End------- 
2023-07-28 15:42:29 [PicList INFO] [PicList Server] is listening at 36677 
2023-07-28 15:42:29 [PicList INFO] File server is running, http://localhost:36699

**Comment by Kuingsmile** [comment]
在两台电脑上均未能复现

**Comment by Kuingsmile** [comment]
试下用node 16.19.0

**Comment by eallion** [comment]
在用 s3 传到 Cloudflare r2，没有这个问题。Win。
